version: "3"
services:
  db:
    image: mysql:8.0.30
    container_name: casebook-mysql-local
    ports:
      - 3606:3306
    environment:
      MYSQL_ROOT_PASSWORD: "admin1234"
      MYSQL_DATABASE: casebook
      MYSQL_USER: casebook_app
      MYSQL_PASSWORD: admin1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/db:/var/lib/mysql  # 데이터베이스 파일을 저장할 디렉토리 (상대 경로)
      - ./database/init-db:/docker-entrypoint-initdb.d  # 초기화 스크립트가 들어있는 디렉토리 (상대 경로)

  redis:
    image: redis:alpine
    command: redis-server --requirepass admin1234 --port 6579
    container_name: casebook-redis-dev
    hostname: redis6579
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6679:6579